# Generated by Django 4.2.13 on 2024-06-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0002_remove_member_author_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='default_first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_alt',
            field=models.URLField(blank=True, null=True),
        ),
    ]
