# Generated by Django 4.2.13 on 2024-06-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0003_member_default_first_name_member_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
