# Generated by Django 4.2.13 on 2024-06-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_app', '0004_member_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='default_first_name',
            new_name='first_name',
        ),
    ]
